# Generated by Django 5.2.1 on 2025-07-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_clubimage_thumbnail_alter_clubimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
